package MainUser;

import java.awt.event.KeyEvent;
import Shopmain.Order;
import Data.DataBase;
import java.util.ArrayList;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cart
 */
public class Login extends javax.swing.JFrame implements Userdata{
    public static Login main;
    public Login() {
        initComponents();
        main = this;
        this.getRootPane().setDefaultButton(toLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toLogin = new javax.swing.JButton();
        ToRegister = new javax.swing.JLabel();
        ShowError = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        toLogin.setText("Login");
        toLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLoginActionPerformed(evt);
            }
        });
        toLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                toLoginKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toLoginKeyReleased(evt);
            }
        });

        ToRegister.setForeground(new java.awt.Color(51, 204, 255));
        ToRegister.setText("Don't have an account?");
        ToRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToRegisterMouseClicked(evt);
            }
        });

        ShowError.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ShowError.setForeground(new java.awt.Color(255, 0, 0));
        ShowError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShowError.setToolTipText("");
        ShowError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });

        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ShowError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addComponent(Password)))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(toLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(ToRegister)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(3, 3, 3)
                .addComponent(toLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLoginActionPerformed
        // TODO add your handling code here:
        Data.readdata();
        DataBase read = new DataBase();
        ArrayList<String> toorderlist = read.readItemData();
        String Usernameinput = Username.getText();
        String Passwordinput = Password.getText();
        if(!(Usernameinput.equals("")) && !(Passwordinput.equals(""))) {
            if ((null != Data.getSelectuser(Usernameinput)) && (Data.getSelectuser(Usernameinput).getPassword().equals(Passwordinput))) {
                ShowError.setText("");
                if (Data.getSelectuser(Usernameinput).getPermission().equals("admin")) {
                    
                    
                    SelectUserManager.username = Usernameinput;
                    SelectUserManager selectuser = new SelectUserManager();
                    selectuser.setLocationRelativeTo(this);
                    selectuser.setVisible(true);
//                    MultiUserManager manage = new MultiUserManager();
//                        manage.setLocationRelativeTo(this);
//                        manage.setVisible(true);
//                        this.dispose();
                } else {
                    Order Ordertable = new Order(Usernameinput);
                    Ordertable.Table(toorderlist);
                    User userset = Data.getSelectuser(Usernameinput);
                    Object[] sendtoorder = {userset.getUsername(),userset.getPoint(),userset.getMoney()};
     //               System.out.println(sendtoorder[0].toString()+sendtoorder[1].toString()+sendtoorder[2].toString());
                    Ordertable.getUserList(sendtoorder);
                    Ordertable.setUsername(userset.getUsername());
                    Ordertable.setLocationRelativeTo(this);
                    Ordertable.show();
                    Ordertable.setVisible(true);
                    this.dispose();
                }   
                
               //space for shopinterface
               
           } else {
                 ShowError.setText("You just enter worng Username or Password!");
           }
        } else {
            ShowError.setText("Please fill all the information");
        }
       
        
        
    }//GEN-LAST:event_toLoginActionPerformed

    private void ToRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToRegisterMouseClicked
        // TODO add your handling code here:
        Register newacc = new Register();
        newacc.setLocationRelativeTo(this);
        newacc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ToRegisterMouseClicked

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            Password.setEchoChar((char)0);
        } else {
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void toLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toLoginKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_toLoginKeyReleased

    private void toLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toLoginKeyPressed
        // TODO add your handling code here:
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//             String Usernameinput = Username.getText();
//        String Passwordinput = Password.getText();
//        if(!(Usernameinput.equals("")) && !(Passwordinput.equals(""))) {
//            if ((null != Data.getSelectuser(Usernameinput)) && (Data.getSelectuser(Usernameinput).getPassword().equals(Passwordinput))) {
//                ShowError.setText("");
//                if (Data.getSelectuser(Usernameinput).getPermission().equals("admin")) {
//                    MultiUserManager manage = new MultiUserManager();
//                        manage.setLocationRelativeTo(this);
//                        manage.setVisible(true);
//                        this.dispose();
//                }   
//                
//               //space for shopinterface
//               
//           } else {
//                 ShowError.setText("You just enter worng Username or Password!");
//           }
//        } else {
//            ShowError.setText("Please fill all the information");
//        }
//        }
    }//GEN-LAST:event_toLoginKeyPressed

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Data.readdata();
             DataBase read = new DataBase();
            ArrayList<String> toorderlist = read.readItemData();
             String Usernameinput = Username.getText();
        String Passwordinput = Password.getText();
        
        if(!(Usernameinput.equals("")) && !(Passwordinput.equals(""))) {
            
            if ((null != Data.getSelectuser(Usernameinput)) && (Data.getSelectuser(Usernameinput).getPassword().equals(Passwordinput))) {
                
                ShowError.setText("");
                
                    if (Data.getSelectuser(Usernameinput).getPermission().equals("admin")) {
                        
                    SelectUserManager.username = Usernameinput;
                    SelectUserManager selectuser = new SelectUserManager();
                    selectuser.setLocationRelativeTo(this);
                    selectuser.setVisible(true);
//                    MultiUserManager manage = new MultiUserManager();
//                        manage.setLocationRelativeTo(this);
//                        manage.setVisible(true);
//                        this.dispose();


                } else {
                    Order Ordertable = new Order(Usernameinput);
                    Ordertable.Table(toorderlist);
                    User userset = Data.getSelectuser(Usernameinput);
                    Object[] sendtoorder = {userset.getUsername(),userset.getPoint(),userset.getMoney()};
                    Ordertable.getUserList(sendtoorder);
                    Ordertable.setUsername(userset.getUsername());
                    Ordertable.setLocationRelativeTo(this);
                    Ordertable.show();
                    Ordertable.setVisible(true);
                    this.dispose();
                }   

           } else {
                 ShowError.setText("You just enter worng Username or Password!");
           }
        } else {
            ShowError.setText("Please fill all the information");
        }
       
        }
    }//GEN-LAST:event_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Data.createadmin();
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel ShowError;
    private javax.swing.JLabel ToRegister;
    private javax.swing.JTextField Username;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton toLogin;
    // End of variables declaration//GEN-END:variables
}
